### PR TITLE
cookie state

### PR DESCRIPTION
**Pull request by markhuot**
We have a nice stateful spot to store cookies on the `test()` so I dropped it there. Seems to work. Need to get all the test passing.

### CODE REVIEW

**Comment by markhuot** [comment]
Woo @ostark, passing tests here. Haven’t tried it within commerce yet, though…

**Comment by ostark** [comment]
This is looks fantastic!
Unfortunately it does not fix the commerce checkout test, it must be something different.

**Comment by ostark** [comment]
Finally, passing tests for all 6 checkout steps !!!

**Comment by markhuot** [comment]
Added in docs for the feature.

I think the `.twig` tests cover what you have in the module. Mind if I remove the module if it’s duplicated by the template logic in the tests?

**Comment by ostark** [comment]
Adjust it as you like @markhuot

**Comment by markhuot** [comment]
For some reason GitHub is breaking the docs build. It’s getting really confused by all these remotes. I created a new PR with your commits and solely on `markhuot/craft-pest` and that seems to be working better. Going to close this PR.

https://github.com/markhuot/craft-pest/pull/60

**Pull request closed without merging**
